META_REVIEW_NODE = "MetaReview"
REVIEW_NODE = "Review"
RATING_NODE = "Rating"
CONFIDENCE_NODE = "Confidence"

CONTAINS_RELATIONSHIP = "CONTAINS"
HAS_RATING_RELATIONSHIP = "HAS_RATING"
HAS_CONFIDENCE_RELATIONSHIP = "HAS_CONFIDENCE"
